/* ============================================================
   Export — Markdown generation + delivery
   Loaded before app.js. Reads `state`, writes nothing to it.
   ============================================================ */

'use strict';

/* ── Vault conventions ───────────────────────────────────── */

const VAULT_QC_FOLDER = '10 4th Street Roastery/02 Roast Logs & QC';

/** Characters Windows forbids in filenames. */
const sanitize = s => s.replace(/[\\/:*?"<>|]/g, '').replace(/\s+/g, ' ').trim();

const pad = n => String(n).padStart(3, '0');
const dateOnly = d => (d || '').slice(0, 10);

/** '2026-08-09T08:00' → '2026-08-09 08:00' */
const readableDate = d => (d || '-').replace('T', ' ');

/**
 * Maps an app verdict onto the QC Log's own status vocabulary.
 * Under-rested batches take the PRELIM form — the log's convention for
 * an observation recorded under an unresolved confound.
 */
function qcStatus(verdict, rested) {
  if (!rested) return verdict === 'pass' ? '🔶 **PRELIM PASS**' : '🔶 **PRELIM FAIL**';
  return {
    pass:   '**PASS**',
    pulled: '**FAIL (Pulled Shot)**',
    fail:   '**FAIL**'
  }[verdict] || '⏳ **PENDING CUP**';
}

/* ── Blockers ────────────────────────────────────────────── */

/** Returns a human reason the session can't be exported, or null if it can. */
function exportBlocker() {
  if (state.mode === 'screening') {
    if (!state.batches.length) return 'No batches generated yet.';

    const unnamed = state.lots.filter(l => !(l.lotName || '').trim()).length;
    const unscored = state.batches.filter(b => b.verdict == null).length;
    const noReason = state.batches.filter(b => b.verdict === 'fail' && !b.reason).length;

    if (unnamed) return `${unnamed} lot${unnamed > 1 ? 's' : ''} missing a name.`;
    if (unscored) return `${unscored} batch${unscored > 1 ? 'es' : ''} not yet evaluated.`;
    if (noReason) return `${noReason} fail${noReason > 1 ? 's' : ''} missing a defect cause.`;
    return null;
  }

  const unscored = state.samples.filter(s => cvaScore(s.affective, s.cups) == null).length;
  if (unscored) return `${unscored} sample${unscored > 1 ? 's' : ''} not fully scored.`;
  return null;
}

/* ── Markdown: batch screening ───────────────────────────── */

function screeningMarkdown() {
  const lots = state.lots;
  const all = state.batches;
  const cupped = dateOnly(state.session.date);

  const overall = tally(all);
  const isRested = l => {
    const h = restHours(l.roastDate, state.session.date);
    return Number.isFinite(h) && h >= REST_GATE_HOURS;
  };
  const hoursOf = l => {
    const h = restHours(l.roastDate, state.session.date);
    return Number.isFinite(h) ? h : null;
  };

  const underRested = lots.filter(l => !isRested(l));
  const uniqueNames = [...new Set(lots.map(l => (l.lotName || '').trim() || 'Unnamed lot'))];

  const subject = uniqueNames.length === 1
    ? `${uniqueNames[0]} — ${lots.length} profile${lots.length > 1 ? 's' : ''}`
    : `${lots.length} lots`;

  const title = `(C) Cupping Session — ${cupped} — ${subject}`;

  const reasons = {};
  all.forEach(x => { if (x.reason) reasons[x.reason] = (reasons[x.reason] || 0) + 1; });
  const reasonRows = Object.entries(reasons).sort((a, c) => c[1] - a[1]);

  const lines = [];

  lines.push(
    '---',
    'type: cupping-session',
    'mode: batch-screening',
    'project: 4th Street Roastery',
    `cupped: ${cupped}`,
    `taster: ${state.session.taster}`,
    `lots: ${lots.length}`,
    `batches: ${all.length}`,
    `pass_rate: ${overall.passRate}`,
    `status: ${underRested.length ? 'preliminary' : 'binding'}`,
    'profiles:'
  );

  lots.forEach(l => lines.push(`  - "${(l.lotName || 'Unnamed lot')} / ${l.profile || '-'}"`));

  lines.push(
    'tags:',
    '  - business/operations',
    '  - coffee/sensory',
    '  - org/4th-street',
    '---',
    '',
    `# ${title}`,
    '',
    '> App-generated by Cupping QC. Batch screening mode — **no CVA score is produced**;',
    '> three of eight affective attributes cannot yield one. Verdicts are direct calls.',
    ''
  );

  if (underRested.length) {
    lines.push(
      '> [!warning] 🔶 PRELIM — one or more lots rested under 72 h',
      ...underRested.map(l => {
        const h = hoursOf(l);
        return `> - **${lotLabel(l)}** — ${h == null ? 'no roast date' : `${h} h off roast`}`;
      }),
      '>',
      '> Sharp acidity and suppressed sweetness are normal at this age and are indistinguishable',
      '> from underdevelopment. **No binding disposition for these lots.** Re-cup at day 5–7.',
      ''
    );
  }

  lines.push(
    '## Summary',
    '',
    `- **Lots screened:** ${lots.length} · **Batches:** ${all.length}`,
    `- **Hopper & Client:** ${overall.pass} · **Pulled Shot:** ${overall.pulled} · **FAIL:** ${overall.fail}`,
    `- **Overall pass rate:** ${overall.passRate}%`,
    ''
  );

  /* per-lot comparison — the reason for screening several profiles together */
  if (lots.length > 1) {
    lines.push(
      '## By lot / profile',
      '',
      '| Lot | Profile | Batches | Pass | Pulled Shot | Fail | Pass rate | Rest |',
      '|---|---|---|---|---|---|---|---|'
    );

    const ranked = lots.map(l => ({ l, t: tally(batchesOf(l.id)) }))
      .sort((a, c) => c.t.passRate - a.t.passRate);

    ranked.forEach(({ l, t }) => {
      const h = hoursOf(l);
      lines.push(`| ${l.lotName || 'Unnamed lot'} | ${l.profile || '-'} | ${t.total} | ${t.pass} | ${t.pulled} | ${t.fail} | ${t.scored ? `${t.passRate}%` : '—'} | ${h == null ? '—' : `${h} h`} |`);
    });

    lines.push('');

    const best = ranked[0], worst = ranked[ranked.length - 1];
    const gap = best.t.passRate - worst.t.passRate;

    if (gap >= 20 && ranked.every(r => r.t.scored === r.t.total && r.t.total > 0)) {
      lines.push(
        '> [!note] Profile spread',
        `> **${lotLabel(best.l)}** passed ${best.t.passRate}% against **${lotLabel(worst.l)}** at ${worst.t.passRate}%`,
        `> — a ${gap}-point gap across ${best.t.total} and ${worst.t.total} batches.`,
        '>',
        '> Batch counts this small move fast. Confirm the pattern across further runs before',
        '> treating it as a profile difference rather than run-to-run variance.',
        ''
      );
    }
  }

  if (overall.pass === 0 && all.length) {
    lines.push(
      '> [!danger] Zero batches passed',
      `> None of the ${all.length} batches reached Hopper & Client standard across any profile.`,
      '> A failure spanning every lot points at a shared cause — green, instrumentation, or',
      '> environment — not at individual profiles. **Do not adjust profiles off this result alone.**',
      ''
    );
  }

  if (reasonRows.length) {
    lines.push('## Defect causes', '', '| Cause | Count |', '|---|---|');
    reasonRows.forEach(([r, c]) => lines.push(`| ${r} | ${c} |`));
    lines.push('');
  }

  /* per-lot batch detail */
  lines.push('## Per-batch results', '');

  lots.forEach(l => {
    const batches = batchesOf(l.id);
    const h = hoursOf(l);

    lines.push(
      `### ${lotLabel(l)}`,
      '',
      `${[l.origin, l.process, `roasted ${readableDate(l.roastDate)}`, h == null ? 'rest unknown' : `rested ${h} h`].filter(Boolean).join(' · ')}`,
      '',
      '| Batch | Verdict | Acidity | Sweetness | Body | Defect cause |',
      '|---|---|---|---|---|---|'
    );

    batches.forEach(x => {
      const v = verdictOf(x.verdict);
      lines.push(`| #${pad(x.no)} | ${v ? v.full : 'Not evaluated'} | ${x.attrs.Acidity ?? '–'} | ${x.attrs.Sweetness ?? '–'} | ${x.attrs.Body ?? '–'} | ${x.reason || '—'} |`);
    });

    lines.push('');
  });

  lines.push(
    '> Acidity / Sweetness / Body are **trend indicators on a 1–9 quality scale**, not cup scores.',
    '',
    '## Rows for QC Log Part 2',
    '',
    'Paste beneath the existing table in [[(C) Quality Control (QC) Log]].',
    '',
    '```markdown'
  );

  lots.forEach(l => {
    const rested = isRested(l);
    batchesOf(l.id).forEach(x => {
      const note = [x.reason, `A/S/B ${x.attrs.Acidity ?? '–'}/${x.attrs.Sweetness ?? '–'}/${x.attrs.Body ?? '–'}`]
        .filter(Boolean).join(' · ');
      lines.push(
        `| ${cupped} | #${pad(x.no)} | ${l.lotName || 'Unnamed lot'} (${l.process || '-'}) | **Profile ${l.profile || '-'}** | - | - | - | - | ${qcStatus(x.verdict, rested)} | ${note} |`
      );
    });
  });

  lines.push('```', '', '---', '[[(C) Quality Control (QC) Log]] · [[(C) 4th Street — INDEX]]', '');

  return { filename: `${sanitize(title)}.md`, content: lines.join('\n') };
}

/* ── Markdown: table cupping ─────────────────────────────── */

function calibrationMarkdown() {
  const cupped = dateOnly(state.session.date);
  const title = `(C) Cupping Session — ${cupped} — Table Cupping`;

  const ranked = state.samples
    .map(s => ({ s, score: cvaScore(s.affective, s.cups) }))
    .sort((a, c) => (c.score ?? -Infinity) - (a.score ?? -Infinity));

  const lines = [];

  lines.push(
    '---',
    'type: cupping-session',
    'mode: table-cupping',
    'project: 4th Street Roastery',
    `cupped: ${cupped}`,
    `location: ${state.session.location}`,
    `taster: ${state.session.taster}`,
    `samples: ${state.samples.length}`,
    `top_score: ${ranked[0]?.score ?? '-'}`,
    'tags:',
    '  - business/operations',
    '  - coffee/sensory',
    '  - org/4th-street',
    '---',
    '',
    `# ${title}`,
    '',
    '> App-generated by Cupping QC. Scores per **SCA Standard 104-2024** (CVA affective).',
    `> \`0.65625 × Σ(8 sections) + 52.75 − 2·nonUniform − 4·defective\``,
    '',
    '## Ranking',
    '',
    '| # | Coffee | Score | Defect cups | Disposition |',
    '|---|---|---|---|---|'
  );

  ranked.forEach((r, i) => {
    const defective = r.s.cups.filter(c => c === 'defective').length;
    const winner = i === 0 && r.score != null;
    lines.push(`| ${i + 1} | ${nameOf(r.s)}${winner ? ' ★' : ''} | ${fmtScore(r.score)} | ${defective} / 3 | ${disposition(r.s).label} |`);
  });

  lines.push('', '## Per-sample detail', '');

  ranked.forEach(r => {
    const s = r.s;
    const hrs = restHours(s.roastDate, state.session.date);

    lines.push(
      `### ${nameOf(s)} — ${fmtScore(r.score)}`,
      '',
      `- **Origin:** ${s.origin || '-'} · **Process:** ${s.process || '-'}`,
      `- **Profile:** ${s.profile || '-'} · **Batch:** ${s.batchNo || '-'} · **Rested:** ${Number.isFinite(hrs) ? `${hrs} h` : 'unknown'}`,
      `- **Cups:** ${s.cups.join(', ')}`,
      '',
      '| Attribute | Intensity (0–15) | Quality (1–9) |',
      '|---|---|---|'
    );

    AFFECTIVE_ATTRS.forEach(a => {
      const int = INTENSITY_ATTRS.includes(a) ? s.intensity[a] : '—';
      lines.push(`| ${a} | ${int} | ${s.affective[a] ?? '–'} |`);
    });

    lines.push('');
  });

  lines.push(
    '## Rows for QC Log Part 2',
    '',
    '```markdown'
  );

  ranked.forEach(r => {
    const s = r.s;
    const rested = restHours(s.roastDate, state.session.date) >= REST_GATE_HOURS;
    const status = rested
      ? (disposition(s).tone === 'good' ? '**PASS**' : '**FAIL (Pulled Shot)**')
      : '🔶 **PRELIM**';
    lines.push(`| ${cupped} | ${s.batchNo || '-'} | ${nameOf(s)} (${s.process || '-'}) | **Profile ${s.profile || '-'}** | - | - | - | ${fmtScore(r.score)} | ${status} | CVA ${fmtScore(r.score)} |`);
  });

  lines.push('```', '', '---', '[[(C) Quality Control (QC) Log]] · [[(C) 4th Street — INDEX]]', '');

  return { filename: `${sanitize(title)}.md`, content: lines.join('\n') };
}

const buildExport = () => state.mode === 'screening' ? screeningMarkdown() : calibrationMarkdown();

/* ── Delivery ────────────────────────────────────────────── */

const canSaveToVault = () => typeof window.showDirectoryPicker === 'function';

async function copyMarkdown() {
  const { content } = buildExport();
  try {
    await navigator.clipboard.writeText(content);
    return 'Copied to clipboard.';
  } catch {
    // Clipboard API needs a secure context; fall back to the old path.
    const ta = document.createElement('textarea');
    ta.value = content;
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.append(ta);
    ta.select();
    const ok = document.execCommand('copy');
    ta.remove();
    return ok ? 'Copied to clipboard.' : 'Copy failed — use Download instead.';
  }
}

function downloadMarkdown() {
  const { filename, content } = buildExport();
  const url = URL.createObjectURL(new Blob([content], { type: 'text/markdown;charset=utf-8' }));
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.append(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  return `Downloaded ${filename}`;
}

async function ensureVaultDir() {
  let handle = await kvGet('vaultDir');

  if (handle) {
    const perm = await handle.queryPermission({ mode: 'readwrite' });
    if (perm !== 'granted') {
      const asked = await handle.requestPermission({ mode: 'readwrite' });
      if (asked !== 'granted') handle = null;
    }
  }

  if (!handle) {
    handle = await window.showDirectoryPicker({ mode: 'readwrite' });
    await kvSet('vaultDir', handle);
  }

  return handle;
}

async function saveToVault() {
  const { filename, content } = buildExport();
  const dir = await ensureVaultDir();

  // Never clobber an existing note — suffix instead.
  let name = filename;
  let n = 2;
  while (await dir.getFileHandle(name).then(() => true).catch(() => false)) {
    name = filename.replace(/\.md$/, ` (${n++}).md`);
  }

  const file = await dir.getFileHandle(name, { create: true });
  const writable = await file.createWritable();
  await writable.write(content);
  await writable.close();

  return `Saved ${name} to ${dir.name}/`;
}
